name: Cerberos - Laravel CI

on:
  # Run on push to Master (should not happen).
  push:
    branches:
      - master

    # Run when any tag is created.
    tags:
      - '*'

  # Run on PR's for master when Opened, Reopened or Synchronized.
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  cerberos-laravel-ci:
    strategy:
      matrix:
        php-version: [ 8.2 ]
        node-version: [ 20 ]

    # Inherit secrets makes sure we use the secrets from this workflow in the called workflow
    secrets: inherit
    uses: cerberos-dev/cerberos-internal/.github/workflows-examples/cerberos.laravel-ci.yml@1.0.1
    with:
      php-version: ${{ matrix.php-version }}
      node-version: ${{ matrix.node-version }}
